# Generated by Django 3.2.18 on 2023-04-14 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dislike_user',
            field=models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
